apiVersion: apps.clusternet.io/v1alpha1
kind: Announcement
metadata:
  name: helm-app-mysql
spec:
  clusterAffinity:
    matchLabels:
      clusters.clusternet.io/cluster-id: cae6feb5-a23f-4354-8ee7-66527aa03f54
  chartSelectors:
    - name: helm-app-mysql
